# Set to true to use lowercase keywords instead of uppercase.
lowercaseKeywords: false
connections:
  - alias: merp_test.db
    driver: sqlite3
    dataSourceName: file:/home/zyr/work/merp_api/sqlite3/test.db
