return {
  'nanotee/sqls.nvim',
  -- require'lspconfig'.sqls.setup{
  --   settings = {
  --     sqls = {
  --       connections {
  --         {
  --           driver = 'sqlite3',
  --           dataSourceName = '~/work/merp_api/pkg/database/test.db'
  --         },
  --       },
  --     },
  --   },
  -- },
  -- on_attach = function (client, bufnr)
  --   require('sqls').on_attach(client, bufnr)
  -- end
  -- require('lspconfig').sqls.setup{
  --       settings = {
  --           sqls = {
  --               connections {
  --                   {
  --                       driver = 'sqlite3',
  --                       dataSourceName = 'file:test.db'
  --                   },
  --               },
  --           },
  --       },
  --   on_attach = function (client, bufnr)
  --     require('sqls').on_attach(client, bufnr)
  --   end
  -- }
}
